theme: jekyll-theme-cayman
title: SecBase
description: Protect your Personal Identifiable Information
plugins:
#  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links

  - jekyll-remote-theme

  - jekyll-sitemap
  - jekyll-seo-tag

remote_theme: pages-themes/cayman@v0.2.0
show_downloads: false
google_analytics: G-Q2E0ZC3GJF
